---
- hosts: www
  gather_facts: False

  vars:
    - root_dir: "{{playbook_dir}}"
    - env: prod
    - custom_demo_domain: "{{ansible_host}}"
    - gogs_mysql_databases:
        - name: gogs
          encoding: utf8
          collation: utf8_unicode_ci
    - gogs_mysql_users:
        - name: gogs
          host: "localhost"
          password: gogs
          priv: "gogs.*:ALL"

    - gogs_custom_app_ini:
        main:
          APP_NAME: 'Gogs: Go Git Service'
          RUN_USER: 'git'
          RUN_MODE: '{{env}}'
        repository:
          ROOT: ''
          SCRIPT_TYPE: 'bash'
        server:
          PROTOCOL: 'http'
          DOMAIN: '{{custom_demo_domain}}'
          ROOT_URL: '%(PROTOCOL)s://%(DOMAIN)s:%(HTTP_PORT)s/'
          HTTP_ADDR: ''
          HTTP_PORT: '3000'
          SSH_PORT: '22'
          OFFLINE_MODE: false
          DISABLE_ROUTER_LOG: false
#          CERT_FILE: 'custom/https/cert.pem'
#          KEY_FILE: 'custom/https/key.pem'
          STATIC_ROOT_PATH: ''
          ENABLE_GZIP: false
          LANDING_PAGE: 'home'
        database:
          DB_TYPE: mysql
          HOST: 127.0.0.1:3306
          NAME: gogs
          USER: gogs
          PASSWD: 'gogs'
          SSL_MODE: 'disable'
#          PATH: 'data/gogs.db'
        security:  # comment to activate wizard
          INSTALL_LOCK = true
          SECRET_KEY   = LwZQ0q4f1DYQKlZ


  pre_tasks:
    - debug: msg="Pre tasks section"

    - name: ANSIBLE PYTHON | install python 2
      raw: test -e /usr/bin/python || (apt -qqy update && apt install -qy python-minimal)
      become: yes

    - name:  UNPRIVILEGED USERS | Get acl dependency (ansible unprivileged user operations magic)
      apt: pkg="acl"
      become: yes

    - name: gather facts
      setup:

    - name: Include environment related variables
      include_vars: "{{ item }}"
      ignore_errors: true
      with_first_found:
       - "{{env}}_vars.yml"
       - "local_vars.yml"


  roles:
     - {
         role: "sa-git"
       }
     - {
         role: "sa-nginx"
       }
     - {
         role: "sa-include",
         include_file: "{{root_dir}}/demosite.yml"
       }
     - {
        role: "sa-mysql",
        option_harden_mysql: true,
        mysql_root_user: root,
        mysql_root_password: devroot,
        mysql_databases: "{{gogs_mysql_databases}}",
        mysql_users: "{{gogs_mysql_users}}"
       }
     - {
         role: "sa-gogs",
         gogs_app_ini: "{{gogs_custom_app_ini}}"
       }
